name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy wybthon==0.8.0

      - name: Lint (Ruff)
        run: |
          ruff check app

      - name: Format check (Black)
        run: |
          black --check app

      - name: Type check (MyPy)
        run: |
          mypy app --install-types --non-interactive --ignore-missing-imports

      - name: Validate HTML exists
        run: |
          test -f index.html
          test -f 404.html
