name: Link Check

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker (lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.html' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
